# Generated by Django 2.0 on 2018-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bxslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('img_url', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Bxslider',
                'managed': False,
            },
        ),
    ]
