# Generated by Django 2.0 on 2018-03-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doshow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwMoneyFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_type', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('consume_uin', models.IntegerField()),
                ('accept_uin', models.IntegerField()),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('money', models.IntegerField()),
                ('before_money', models.IntegerField()),
                ('after_money', models.IntegerField()),
                ('mark', models.CharField(blank=True, max_length=200, null=True)),
                ('create_time', models.DateTimeField()),
                ('state', models.IntegerField()),
                ('state_time', models.DateTimeField()),
                ('appflag', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'dw_money_flow',
            },
        ),
        migrations.CreateModel(
            name='PresentPropTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromuin', models.PositiveIntegerField()),
                ('touin', models.PositiveIntegerField()),
                ('ownuin', models.PositiveIntegerField()),
                ('propid', models.PositiveIntegerField()),
                ('propnum', models.PositiveIntegerField()),
                ('sendbean', models.PositiveIntegerField()),
                ('receivebean', models.PositiveIntegerField()),
                ('ownbean', models.PositiveIntegerField()),
                ('discount', models.FloatField()),
                ('taxbean', models.PositiveIntegerField()),
                ('fromremainbean', models.PositiveIntegerField()),
                ('toremainbean', models.PositiveIntegerField()),
                ('ownremainbean', models.PositiveIntegerField()),
                ('createtime', models.DateTimeField()),
                ('toflag', models.PositiveIntegerField()),
                ('ownflag', models.PositiveIntegerField()),
                ('curcount', models.IntegerField()),
                ('subownuin', models.PositiveIntegerField(blank=True, null=True)),
                ('subownbean', models.PositiveIntegerField(blank=True, null=True)),
                ('subdiscount', models.FloatField(blank=True, null=True)),
                ('subownremainbean', models.PositiveIntegerField(blank=True, null=True)),
                ('rootroomid', models.PositiveIntegerField(blank=True, null=True)),
                ('roomid', models.PositiveIntegerField(blank=True, null=True)),
                ('appflag', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'present_prop_tbl',
            },
        ),
    ]
