# Generated by Django 2.0 on 2018-04-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doshow', '0003_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
