# Generated by Django 2.0 on 2018-04-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doshow', '0005_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTbl',
            fields=[
                ('uin', models.AutoField(primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=16)),
                ('pic', models.PositiveIntegerField()),
                ('nick', models.CharField(max_length=16, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=16)),
                ('province', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('auth', models.PositiveIntegerField()),
                ('msg_id', models.PositiveIntegerField()),
                ('search', models.PositiveIntegerField()),
                ('oltime', models.PositiveIntegerField()),
                ('userinfo_ver', models.PositiveIntegerField()),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('regfrom', models.PositiveIntegerField()),
                ('resv1', models.PositiveSmallIntegerField()),
                ('resv2', models.PositiveIntegerField()),
                ('resv3', models.CharField(max_length=20)),
                ('resv4', models.CharField(max_length=20)),
                ('signature', models.CharField(blank=True, max_length=41, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=200, null=True)),
                ('last_path', models.CharField(blank=True, max_length=200, null=True)),
                ('photo_flag', models.IntegerField()),
                ('photo_ctime', models.DateTimeField(blank=True, null=True)),
                ('photo_utime', models.DateTimeField(blank=True, null=True)),
                ('avatar_path_large', models.CharField(blank=True, max_length=80, null=True)),
                ('avatar_flag', models.IntegerField(blank=True, null=True)),
                ('avatar_time', models.DateTimeField(blank=True, null=True)),
                ('phone_security', models.CharField(blank=True, max_length=11, null=True)),
                ('phone_ctime', models.DateTimeField(blank=True, null=True)),
                ('phone_utime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'basic_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropTbl',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('bean', models.PositiveIntegerField()),
                ('discount', models.FloatField()),
                ('owndiscount', models.FloatField()),
                ('bonusdiscount', models.FloatField()),
                ('proptypeid', models.PositiveIntegerField()),
                ('createtime', models.DateTimeField()),
                ('proplevel', models.PositiveIntegerField()),
                ('comboeffect', models.IntegerField(blank=True, db_column='comboEffect', null=True)),
                ('conbinativeeffect', models.IntegerField(blank=True, db_column='conbinativeEffect', null=True)),
                ('luckgift', models.IntegerField(blank=True, db_column='luckGift', null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('flashgift', models.IntegerField(blank=True, null=True)),
                ('tip', models.CharField(blank=True, max_length=50, null=True)),
                ('newtip', models.CharField(blank=True, max_length=50, null=True)),
                ('recommend_state', models.IntegerField(blank=True, null=True)),
                ('zhouxing_state', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mobile_activity', models.SmallIntegerField(blank=True, null=True)),
                ('pc_gift_flag', models.IntegerField(blank=True, null=True)),
                ('talk_gift_flag', models.IntegerField(blank=True, null=True)),
                ('phone_gift_flag', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prop_tbl',
                'managed': False,
            },
        ),
    ]
